name: Selenium PoC CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run containers
        run: docker compose up --build -d

      - name: Run tests
        run: docker compose run pytest-tests

      - name: Tear down
        run: docker compose down
